[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm cache clean --force',
  'rm -rf node_modules package-lock.json',
  'npm install --no-package-lock --no-audit --no-fund --omit=dev'
]

[phases.build]
cmds = ['echo "No build step required - static files ready"']

[start]
cmd = 'npm start'